on: 
  push:
    branches: [main]
    tags: ["release-v*"]
jobs:  
  export_game:
    runs-on: ubuntu-latest    
    permissions: write-all # Add permission for release creation.
    env:
        SRCZIPNAME: netpinproc-and-pingod-addons-source-${{ github.ref_name }}.zip
        GAMEZIPNAME: demo-pingod-netpinproc-win-${{ github.ref_name }}.zip
        TAG: ${{ github.ref_name }} 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGETAPIKEY: --api-key ${{ secrets.GITHUB_TOKEN }} --source github
    name: build repository
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: Cloning `pingod-addons`...
      run: | 
          git clone https://github.com/FlippingFlips/pingod-addons
          cd pingod-addons
          git checkout
          cd ..

    - name: Copying `pingod-addons` directory...
      run: |
          cp -R ./pingod-addons/addons .          
          dir
          rm -r ./pingod-addons

    - name: NUGET - FlippingFlips
      run: dotnet nuget add source --username USERNAME --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/FlippingFlips/index.json"

    - name: Zipping `PinGod-Addons`, `NetPinProc-Addons`, `LibPinProc` - All files needed for base game setup
      run: |        
        7z a -tzip "${SRCZIPNAME}" "addons" # add pingod addons
        7z a -tzip "${SRCZIPNAME}" "autoload"
        7z a -tzip "${SRCZIPNAME}" "PinGod-AddOns-NetPinProcGame.csproj"                
        7z a -tzip "${SRCZIPNAME}" "netpinproc-game"
        7z a -tzip "${SRCZIPNAME}" "lib"
        7z a -tzip "${SRCZIPNAME}" "simulators"
        7z a -tzip "${SRCZIPNAME}" "sql"
        7z a -tzip "${SRCZIPNAME}" "README.md"
        7z a -tzip "${SRCZIPNAME}" "project.godot"
        7z a -tzip "${SRCZIPNAME}" "LICENSE.md"
        7z a -tzip "${SRCZIPNAME}" "export_presets.cfg"
      
    - name: godot-export
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.0
      with:        
        cache: true # cache the Godot export templates and Godot executable
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_mono_export_templates.tpz
        relative_project_path: ./        
        archive_output: false # don't archive output, we take care of it
        #wine_path: ${{ steps.wine_install.outputs.WINE_PATH }} # Icons work without using wine - Dave

    - name: check built files
      run: |
        #dir /home/runner/.local/share/godot/builds/win/win.exe
        dir /home/runner/.local/share/godot/builds
        dir /home/runner/.local/share/godot/builds/win

    # pack the executable, 70mb without
    - name: Run UPX Pack Exe
      uses: crazy-max/ghaction-upx@v3
      with:
          version: latest
          files: |
            /home/runner/.local/share/godot/builds/win/win.exe
          args: -fq

    # zip all needed files to run the game out of the box
    - name: Zip
      run: | 
          # zip windows files, this should include a mono directory as well as .exe .pck
          7z a -tzip "${GAMEZIPNAME}"  "/home/runner/.local/share/godot/builds/win/*"

          # add lib files for libpinproc
          7z a -tzip "${GAMEZIPNAME}"  "lib"

          # add sql init files for NetPinproc.Game.Sqlite
          7z a -tzip "${GAMEZIPNAME}"  "sql"

          # zip VP files
          7z a -tzip "${GAMEZIPNAME}" "simulators/visual-pinball/pingodaddons-netpinproc.vpx"
          7z a -tzip "${GAMEZIPNAME}"  "simulators/visual-pinball/pingodaddons-netpinproc.vbs"
          7z a -tzip "${GAMEZIPNAME}"  "simulators/visual-pinball/README.md"
    
    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}        
        generateReleaseNotes: false    
        replacesArtifacts: true
        prerelease: false # Pre release dev flag
        allowUpdates: true # allow the release files to be updated and not create a new release every time
        tag: ${{ github.ref_name }} #Branch name?
        # include exported windows game zip and source project zip
        artifacts: "*.zip"
