on: 
  push:
   branches: [dev]
   #tags:
   #   - "v*"
jobs:
  # job id, can be anything
  export_game:
    runs-on: ubuntu-latest
    # Add permission for release creation.
    permissions: write-all
    env:
        VERSION: 0.99
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGETAPIKEY: --api-key ${{ secrets.GITHUB_TOKEN }} --source github
    name: build repository
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: clone pingod-addons
      run: git clone https://github.com/FlippingFlips/pingod-addons

    - name: copy pingod-addons
      run: |
          dir
          cp -R ./pingod-addons/addons /addons          

    - name: NUGET - FlippingFlips
      run: dotnet nuget add source --username USERNAME --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/FlippingFlips/index.json"

    - name: dotnet build
      run: dotnet build -c Release

    # Copy readme and zip addons directory to release
    - name: zip addons and addons-netpinproc
      run: |        
        7z a -tzip "pingod-addons-netpinproc.zip" "addons"
        7z a -tzip "pingod-addons-netpinproc.zip" "addons-netpinproc"
      
    #- name: export game
    #  id: export
    #  # Use latest version (see releases for all versions)
    #  uses: firebelley/godot-export@v5.2.0
    #  with:
    #    # Defining all the required inputs
    #    godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_linux_x86_64.zip
    #    godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_export_templates.tpz
    #    relative_project_path: ./
    #    archive_output: true

    #  # This release action has worked well for me. However, you can most likely use any release action of your choosing.
    #  # https://github.com/ncipollo/release-action
    #- name: create release
    #  uses: ncipollo/release-action@v1.12.0
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}        
    #    generateReleaseNotes: false
    #    tag: ${{ github.ref_name }}
    #    artifacts: ${{ steps.export.outputs.archive_directory }}/*, pingod-addons-(${{ github.ref_name }}).zip
